version: "3.9"

services:
  web:
    build: .
    command: python3 /Book-Store/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Book-Store
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=django-insecure-sl8(jhd(^i%13&j@-!w79e-_h)9hqx4m@w$$zf02+^#3ws@x)as'
      - 'DJANGO_DEBUG=True'

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    
volumes:    
  postgres_data: